config/routes.rb
AuctionApp::Application.routes.draw do
  resources :categories
  resources :bids
  resources :items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy" 
  
  get "users/new"
  get "users/create"
  get "users/destroy" 
  
  
  root 'items#index'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/help', to: 'static_pages#help', as: 'help'
  
  get '/doc', to: 'static_pages#doc', as: 'doc'
  
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/bids',    to: 'bid#show',             via: 'get'

  

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  validates :user_id, presence: true
  validates :item_id, presence: true
  default_scope order ("created_at DESC")
  validates :amount, :numericality => {:greater_than => 1, :less_than => 9999999}
  
  def self.search(item, user)
    if item != nil && user != nil
      find(:all, conditions: ['item_id = ? AND user_id = ?', item, user])
    elsif !item && user
      find(:all, conditions: ['user_id = ?', user])
    else
      find(:all, conditions: ['item_id = ?', item])
    end
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  
  def create 
    @current_user = User.find(params[:bid][:user_id])
    @item = Item.find(params[:bid][:item_id])
  
  if @current_user.id != @item.vendor_id
    @bid = Bid.new(bid_params)
    if @bid.save
      @item.update(price: @bid.amount)
      flash[:notice] = "New Bid Added"
      redirect_to @item, notice: "You are the highest bidder!"
      @item.starting_price = @bid.amount
    else
      redirect_to @item, notice: "You cannot bid on your own items!"
    end
  end
end

def bid_params
  params.require(:bid).permit(:amount, :user_id, :item_id)
end

def destroy
end

def show
  @id = params[:id]
  @item = Item.find(params[:id])
  @users = User.find(@item.vendor_id)
  @bids = Bid.search(@item.id,nil)
end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
<% if @bid.errors.any? %>
<div>
  <h2><%= pluralize(@bid.errors.count, "error") %> prohibited from being saved:</h2>
  
    <ul>
    <% @bid.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
    <% end %>
    
    <% if signed_in? && @current_user.id != @item.vendor_id %>
    <p>
      <strong>Bid:</strong><td><div class="field">
      <%= f.hidden_field :item_id, value: @item.id %>
      <%= f.hidden_field :user_id, value: @current_user.id %>
      <%= f.number_field :amount, min: @item.price, value: @item.price %>
      <%= f.submit "Place a bid" %>
      </p>
      <% else %>
      <b>Bid: Bid Unavailable</b>
      <% end %>
      <% end %>

app/views/bids/show.html.erb
<div>
  <div>
    <h1> Bidding History </h1>
    <%= link_to "Return to item", item_path(@item) %> <br><br>
    <table>
      <tr>
        <th>Bidder</th>
        <th>Bid Time</th>
        <th>Bid Amount</th>
      </tr>
      <% @bids.each do |bid| %>
      <tr>
        <td><%= User.find(bid.user_id).name %></td>
        <td><%= bid.created_at %></td>
        <td><%= bid.amount %></td>
        <% end %>
      </tr>
    </table>
    <br><br>
  </div>
</div>