config/routes.rb
AuctionApp::Application.routes.draw do
  resources :categories
  resources :bids
  resources :items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy" 
  
  get "users/new"
  get "users/create"
  get "users/destroy" 
  
  
  root 'items#index'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/help', to: 'static_pages#help', as: 'help'
  
  get '/doc', to: 'static_pages#doc', as: 'doc'
  
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/bids',    to: 'bid#show',             via: 'get'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :bids, dependent: :destroy, :foreign_key => :item_id
  belongs_to :category
  validates :name, presence: true
  validates :category, presence: true
  validates :starting_price, presence: true
  

  def self.search(query,searchObjects)
    if query == "" && searchObjects == "" || searchObjects == nil
     find(:all)
    elsif query != "" && searchObjects != "" 
      find(:all, conditions: ['name like ? AND category_id = ? OR description like ? AND category_id = ? ', "%#{query}%", searchObjects, "%#{query}%", searchObjects])
    elsif query != "" && searchObjects == ""
     find(:all, conditions: ['name like ? OR description like ?', "%#{query}%", "%#{query}%"])  
    elsif query == "" && searchObjects != ""
     find(:all, conditions: ['category_id = ?', searchObjects]) 
    else
      find(:all)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ApplicationHelper
  include SessionsHelper
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:new]
  before_action :current_user, only: [:new, :create, :edit, :update, :destroy, :show]
  
  
  # GET /items
  # GET /items.json
  def index
    #setting the parameters for the Item.search
    @items = Item.search(params[:query], params[:searchItems])
    @categoryOpts = category_options
  end

  # GET /items/1
  # GET /items/1.json
  def show
    #category is getting the items.category_id
    @category = Category.find(@item.category_id)
    @bid = Bid.new
    @bids = @item.bids
  end

  # GET /items/new
  def new
    @item = Item.new(:user_id => @user.id)
  end

  # GET /items/1/edit
  def edit
    #category is getting item the catgegories name aswell as id value
    @category = Category.find(@item.category_id).name
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.update(vendor_id: @current_user.id)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :category_id, :vendor, :starting_price)
    end
    
  def category_options 
    #collecting everything from category inclusive of its name and id
    Category.all.collect { |c| [c.name, c.id] } 
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/Index.html.erb
<%= render @items %>
@items = item.all

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :vendor %><br>
    <%= f.text_field :vendor %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select( :category_id, Category.all, :id, :name)%>
  </div>
  <div class="field">
    <%= f.label :starting_price %><br>
    <%= f.text_field :starting_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Search for items</h1>

<%= form_tag items_path, method: 'get' do %>
  <p>
    <%= label_tag :query, "Search for:" %>
    <%= text_field_tag :query, params[:query] %>
    <%= select_tag(:searchItems, options_for_select(@categoryOpts), prompt: 'Please Select:') %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Starting Price</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>      
        <td><%= link_to item.name, item %></td>
        <td><%= item.category.name %></td>
        <td><%= item.starting_price %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Item', new_item_path %>
<br>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @item.vendor %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Starting price:</strong>
  <%= @item.starting_price %>
</p>

<%= render 'bids/form', bid: Bid.new %>
<% if signed_in? && @current_user.id == User.find(@item.vendor_id).id %>
<%= link_to 'Bid_Listing', bid_path(@item) %>
<%= link_to 'Update', edit_item_path(@item) %> |
<%= link_to 'Remove', :item, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
<%= link_to 'Bid_Listing', bid_path(@item) %>
<% end %>