config/routes.rb
AuctionApp::Application.routes.draw do
  resources :categories
  resources :bids
  resources :items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy" 
  
  get "users/new"
  get "users/create"
  get "users/destroy" 
  
  
  root 'items#index'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/help', to: 'static_pages#help', as: 'help'
  
  get '/doc', to: 'static_pages#doc', as: 'doc'
  
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/bids',    to: 'bid#show',             via: 'get'

  

end

app/views/layouts/_footer.html.erb
<hr>
<footer>
<h3>Matheau Starkoff,</h3>
<h3>s2885591,</h3>
<h3>20/1/14</h3>
<%= link_to 'Documentation', doc_path %>
</footer>

app/views/layouts/_header.html.erb
<header>
	<h1> Stark Auction Industries </h1>

   <% if signed_in? %>
        <%= "Welcome to Stark Auction Industries " + @current_user.name + "!"%>
  <br>
        <%= link_to "Home", items_path %> |
	      <%= link_to "Contact", contact_path %> |
	      <%= link_to "About", about_path %> |
	      <%= link_to "Help", help_path %> |
        <%= link_to "Users", users_path %> |  
        <%= link_to "Profile", current_user %> |
        <%= link_to "Logout", signout_path, method: "delete" %>
    <% else %>
        <%= link_to "Home", items_path %> |
	      <%= link_to "Contact", contact_path %> |
	      <%= link_to "About", about_path %> |
	      <%= link_to "Help", help_path %> |
        <%= link_to "Sign up", signup_path %> |
        <%= link_to "Sign in", signin_path %>   

    <% end %>
  <hr/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

</body>
</html>